# Generated by Django 6.0.6 on 2026-07-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
